#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit "$1"

BRANCH_NAME=$(git branch --show-current)
COMMIT_MSG_FILE=$1

if [ -n "$BRANCH_NAME" ] && [ -f "$COMMIT_MSG_FILE" ]; then
  BRANCH_TYPE="[${BRANCH_NAME}]"

  if [ -n "$BRANCH_TYPE" ]; then
    COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

    NEW_COMMIT_MSG="$BRANCH_TYPE $COMMIT_MSG"

    echo "$NEW_COMMIT_MSG" > "$COMMIT_MSG_FILE"
  fi
fi