name: prod-deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: your-aws-region

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build docker image and push to ECR
              uses: docker/build-push-action@v4
              env:
                  DOCKER_BUILDKIT: 1
                  BUILDKIT_PROGRESS: plain
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: your-aws-ecr-url
